<a href="https://www.kaggle.com/code/shrikantlala/basic-eda-irrigation-need?scriptVersionId=313339043" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd, numpy as np
import matplotlib.pyplot as plt

train = pd.read_csv("/kaggle/input/competitions/playground-series-s6e4/train.csv")
print(f"Train shape: {train.shape}")
train.head()

Train shape: (630000, 21)

,id,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,...,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,0,Loamy,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,...,Sugarcane,Sowing,Zaid,Drip,Rainwater,0.82,No,112.16,East,Low
1,1,Clay,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,...,Wheat,Vegetative,Kharif,Rainfed,River,5.27,Yes,47.16,South,Low
2,2,Clay,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,...,Rice,Vegetative,Kharif,Sprinkler,Reservoir,8.24,Yes,110.38,North,Low
3,3,Sandy,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,...,Wheat,Flowering,Kharif,Canal,River,8.32,Yes,53.85,South,Medium
4,4,Clay,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,...,Wheat,Sowing,Rabi,Canal,River,7.37,No,93.19,South,Low

In [2]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630000 entries, 0 to 629999
Data columns (total 21 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       630000 non-null  int64
 1   Soil_Type                630000 non-null  object
 2   Soil_pH                  630000 non-null  float64
 3   Soil_Moisture            630000 non-null  float64
 4   Organic_Carbon           630000 non-null  float64
 5   Electrical_Conductivity  630000 non-null  float64
 6   Temperature_C            630000 non-null  float64
 7   Humidity                 630000 non-null  float64
 8   Rainfall_mm              630000 non-null  float64
 9   Sunlight_Hours           630000 non-null  float64
 10  Wind_Speed_kmh           630000 non-null  float64
 11  Crop_Type                630000 non-null  object
 12  Crop_Growth_Stage        630000 non-null  object
 13  Season                   630000 non-null  object
 14  Irrigation_Type          630000 non-null  object
 15  Water_Source             630000 non-null  object
 16  Field_Area_hectare       630000 non-null  float64
 17  Mulching_Used            630000 non-null  object
 18  Previous_Irrigation_mm   630000 non-null  float64
 19  Region                   630000 non-null  object
 20  Irrigation_Need          630000 non-null  object
dtypes: float64(11), int64(1), object(9)
memory usage: 100.9+ MB

In [3]:
cat = ['Soil_Type','Crop_Type','Crop_Growth_Stage','Season','Irrigation_Type','Water_Source','Mulching_Used','Region']
train[cat]

,Soil_Type,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Mulching_Used,Region
0,Loamy,Sugarcane,Sowing,Zaid,Drip,Rainwater,No,East
1,Clay,Wheat,Vegetative,Kharif,Rainfed,River,Yes,South
2,Clay,Rice,Vegetative,Kharif,Sprinkler,Reservoir,Yes,North
3,Sandy,Wheat,Flowering,Kharif,Canal,River,Yes,South
4,Clay,Wheat,Sowing,Rabi,Canal,River,No,South
...,...,...,...,...,...,...,...,...
629995,Clay,Rice,Sowing,Kharif,Sprinkler,River,No,South
629996,Clay,Sugarcane,Vegetative,Kharif,Drip,Groundwater,Yes,Central
629997,Clay,Potato,Vegetative,Zaid,Canal,Reservoir,Yes,South
629998,Clay,Sugarcane,Vegetative,Zaid,Sprinkler,Groundwater,Yes,East
629999,Loamy,Maize,Harvest,Kharif,Drip,Reservoir,No,West

In [4]:
train[cat].isnull().sum()

Soil_Type            0
Crop_Type            0
Crop_Growth_Stage    0
Season               0
Irrigation_Type      0
Water_Source         0
Mulching_Used        0
Region               0
dtype: int64

In [5]:
num = ['Soil_pH','Soil_Moisture','Organic_Carbon','Electrical_Conductivity','Temperature_C','Humidity','Rainfall_mm','Sunlight_Hours','Wind_Speed_kmh']
train[num]

,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh
0,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,16.79
1,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,3.39
2,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,3.85
3,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,2.31
4,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,13.94
...,...,...,...,...,...,...,...,...,...
629995,6.54,13.45,1.15,1.86,26.65,26.86,1041.33,10.62,18.85
629996,7.03,54.49,0.96,2.35,36.99,88.00,1419.57,9.93,17.99
629997,6.52,11.98,0.93,0.38,37.82,70.98,88.45,8.19,17.25
629998,5.93,42.86,0.33,3.39,34.99,94.58,2433.92,9.88,5.00
629999,7.02,35.36,1.19,0.46,26.92,64.33,1269.55,7.91,2.72

In [6]:
train[num].isnull().sum()

Soil_pH                    0
Soil_Moisture              0
Organic_Carbon             0
Electrical_Conductivity    0
Temperature_C              0
Humidity                   0
Rainfall_mm                0
Sunlight_Hours             0
Wind_Speed_kmh             0
dtype: int64